/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package parametric;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Vector;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.SwingUtilities;
import javax.swing.table.DefaultTableModel;

import FileIO.FileSaveFrame;

import main.MainFrame;

import functionUtility.FunctionUtility;
import graph.graph;


public class ParametricPanelUI extends javax.swing.JPanel {

	private MainFrame registration;
	Vector vecXpoints = new Vector();
	Vector vecYpoints = new Vector();
	Vector vecXline = new Vector();
	Vector vecYline = new Vector();
    //Use a DefaultTableModel instead of the jTable
    //This will allow adding rows to table dynamically
    private JScrollPane scrollPane;
    public static DefaultTableModel model = new DefaultTableModel();
    JTable table = new JTable(model);
	
    public ParametricPanelUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        
        m_ParaTextA = new javax.swing.JTextField();
        m_ParaTextB = new javax.swing.JTextField();
        m_ParaTextC = new javax.swing.JTextField();
        m_ParaTextD = new javax.swing.JTextField();
        m_ParaTextStep = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Parametric Function - f(t) = (A cos Bt, C sin Dt)", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 12))); // NOI18N

        jLabel1.setText("A:");

        jLabel2.setText("B(Degrees):");

        jLabel3.setText("C:");

        jLabel4.setText("D(Degrees):");

        jLabel5.setText("Step:");
        
        m_ParaTextA.setText("1");

        m_ParaTextB.setText("2");

        m_ParaTextC.setText("3");
        m_ParaTextC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                m_ParaTextCActionPerformed(evt);
            }
        });

        m_ParaTextD.setText("2");

        m_ParaTextStep.setText("22.5");


        scrollPane = new JScrollPane(table);

        jLabel8.setText("x");

        jLabel9.setText("y");

        jButton1.setText("Create Points");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Back");

        jButton3.setText("Draw Graph");

        jButton4.setText("Save Points");
		
		model.addColumn("A cos Bt");
        model.addColumn("C sin Dt");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))                            
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(m_ParaTextA, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(m_ParaTextB, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(m_ParaTextC, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(m_ParaTextD, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(m_ParaTextStep, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(46, 46, 46)
                        .addComponent(jLabel9)
                        .addGap(86, 86, 86))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33))))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, m_ParaTextA, m_ParaTextB, m_ParaTextC, m_ParaTextD, m_ParaTextStep});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(m_ParaTextA, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(m_ParaTextB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(m_ParaTextC, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(m_ParaTextD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(m_ParaTextStep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addComponent(scrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jButton4))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {jButton1, jButton2, jButton3, jButton4, m_ParaTextA, m_ParaTextB, m_ParaTextC, m_ParaTextD, m_ParaTextStep});

        jTabbedPane1.addTab("Values", jPanel2);

      
        jTabbedPane1.addTab("Graph", jPanel3);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        table.setEnabled(false);
        jButton3.setEnabled(false);
		jButton4.setEnabled(false);
        jButton2.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				if (registration != null) {
					 jButton3.setEnabled(false);
						jButton4.setEnabled(false);
					clearTable();
					registration.swapView("menu");
				}
			}
		});

		jButton4.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				SwingUtilities.invokeLater(new Runnable() {
					public void run() {
						String plotPoints = "";
						String function = "("+m_ParaTextA.getText() + " cos "+m_ParaTextB.getText()+"t, "+m_ParaTextC.getText()+ " sin "+m_ParaTextD.getText()+"t)";
						String linePoints = "";
						for(int i = 0; i < model.getRowCount(); i++){
							plotPoints +=model.getValueAt(i, 0).toString()+";"+model.getValueAt(i, 1).toString()+";";
						}
						for(int i = 0; i < vecXline.size(); i++){
							linePoints +=vecXline.get(i).toString()+";"+vecYline.get(i).toString()+";";
						}
						new FileSaveFrame(function,plotPoints, linePoints);
						
					}
				});
			}
		});
		jButton3.addActionListener(new ActionListener() {
			public void actionPerformed(ActionEvent e) {
				jPanel3.removeAll();
				String function = "("+m_ParaTextA.getText() + " cos "+m_ParaTextB.getText()+"t, "+m_ParaTextC.getText()+ " sin "+m_ParaTextD.getText()+"t)";
				graph graph = new graph(vecXpoints, vecYpoints, vecXline, vecYline, function);
				jTabbedPane1.setSelectedIndex(1);
				jPanel3.setOpaque(true);
				jPanel3.add(graph);

				jPanel3.repaint();

				jPanel3.setVisible(true);
				
			}
		});
    }// </editor-fold>//GEN-END:initComponents

    private void m_ParaTextCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_m_ParaTextCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_m_ParaTextCActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //NEEDED:
        // Validation (doubles and ints only) 

        //Variables
        float t_min, t_max, a, b, c, d, step, stepline;
        float t;
        float newX;
        float newY;


		if(!vecXpoints.isEmpty()){	
			vecXpoints.removeAllElements();
			vecYpoints.removeAllElements();
			vecXline.removeAllElements();
			vecYline.removeAllElements();	
		}

       
        clearTable();
        //Get values for variables
        a = Float.parseFloat(m_ParaTextA.getText());
        b = Float.parseFloat(m_ParaTextB.getText());
        c = Float.parseFloat(m_ParaTextC.getText());
        d = Float.parseFloat(m_ParaTextD.getText());
        step = Float.parseFloat(m_ParaTextStep.getText());
        t_min = 0;
        t_max = 360;
        stepline = (t_max - t_min)/1000;

        
        //Loop through and calculate values
        for (float i = t_min; i <= t_max; i = (i + step)) {
            //t, for parametric function
            t = i;
            //call parametric function
            newX = FunctionUtility.ParametricFunctionX(a, b,t);
            newY = FunctionUtility.ParametricFunctionY(c, d,t);
            //Add f(x) and function values to table
            model.addRow(new Object[]{newX, newY});
            //copy into x array
            vecXpoints.add(newX);
            //copy into y array
            vecYpoints.add(newY);
        }
        for (float i = t_min; i <= t_max; i = (i + stepline)) {
			// call poly function
        	 t = i;
             //call parametric function
             newX = FunctionUtility.ParametricFunctionX(a, b,t);
             newY = FunctionUtility.ParametricFunctionY(c, d,t);
			// copy into x array
			vecXline.add(newX);
			// copy into y array
			
			vecYline.add(newY);
		}
        jButton3.setEnabled(true);
		jButton4.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed
    public void setRegistration(MainFrame registration) {
		this.registration = registration;

	}
    public void clearTable() {
		for (int i = model.getRowCount() - 1; i > -1; i--) {
			model.removeRow(i);
		}
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField m_ParaTextA;
    private javax.swing.JTextField m_ParaTextB;
    private javax.swing.JTextField m_ParaTextC;
    private javax.swing.JTextField m_ParaTextD;
    private javax.swing.JTextField m_ParaTextStep;
    // End of variables declaration//GEN-END:variables
}
